### ISSUE TITLE
Can we wrap lines if possible ?

### ISSUE THREAD

**Issue by aiic03** [akiran/react-highlight#28]
It looks like a horizontal scroller is hard to eliminate, due to a long line of code.

![image](https://cloud.githubusercontent.com/assets/11695765/25038374/249682dc-2131-11e7-9a93-34e5142dc7fc.png)

**Comment by briancappello** [comment]
@NEtOrnANtHeR Try adding some CSS:
```css
pre {
    word-break: break-all;
    word-wrap: break-word;
}
```
